config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :customers, only:[:index,:show]
    resources :genres, only:[:new,:create,:edit,:update,:destroy]
    resources :contacts, only:[:index,:edit,:update,:destroy]
    resources :contacts, only:[:index,:new]
  end
  root to: 'homes#top'

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :customer do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations:"public/registrations",
    passwords:'public/settings/passwords',
    sessions:"public/sessions",
    omniauth_callbacks:"public/omniauth_callbacks"
  }


  namespace :public do
    get "/customers/my_page" => "customers#show", as: 'my_page' #会員情報詳細ページ（マイページ）表示
    resources :customers, only:[:edit,:update]
    resources :day_randoms, only:[:new,:create,:show]
    resources :menus, only:[:new,:create,:index,:show,:edit,:update,:destroy]
    resources :week_randoms, only:[:new,:create,:show]
    resources :contacts, only:[:new,:create]
    get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe' #退会確認画面
    patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal' #論理削除用ルーティング
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :customer

  has_many :notifications, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  has_many:menus, dependent: :destroy
  has_many :contact, dependent: :destroy

  validates :name, presence: true

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def self.guest
    find_or_create_by!(name:'guestuser', email:'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def self.from_omniauth(auth)
    customer = find_by(email: auth.info.email)
    if customer
      customer.update(provider: auth.provider, uid: auth.uid)
    end

    where(provider: auth.provider, uid: auth.uid).first_or_create do |customer|
      customer.name = auth.info.name
      customer.email = auth.info.email
      customer.password = Devise.friendly_token[0,20]
    end
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :menus
  validates :name, presence: true, uniqueness: true
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_one_attached :image
  belongs_to :customer
  belongs_to :genre

  enum food_status: {breakfast:0,lunch:1,dinner:2}

  validates :name, presence: true
  validates :introduction, presence: true
  validates :syusyoku, presence: true
  validates :syusai, presence: true
  validates :fukusai, presence: true
  validates :food_status, presence: true
  validates :genre_id, presence: true
  
end

app/models/notification.rb
class Notification < ApplicationRecord
    
    belongs_to :contact
    
    def self.confirmed
        unchecked_notifications = where(checked: false) 
        unchecked_notifications.each do |un|
          un.update!(checked: true)
        end
    end 
end  

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all
    @contacts = Contact.page(params[:page]).order(created_at: :desc).per(10)
    Notification.confirmed
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])
    @contact.update(contact_params)
    @customer = @contact.customer
    ChatMailer.send_when_admin_reply(@customer,@contact).deliver_now
    redirect_to admin_customers_path
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    @contacts = Contact.page(params[:page]).order(created_at: :desc).per(10)
    @customers = Customer.all
    render :index
  end

  private

  def contact_params
    params.require(:contact).permit(:title,:body,:reply)
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
    @menus = @customer.menus.page(params[:page])
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def new
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to new_admin_genre_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to new_admin_genre_path
  end
  
  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to request.referer
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController

  def after_sign_in_path_for(resource)
    admin_customers_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :check_notifications
  def check_notifications
    @unchecked_notifications = Notification.where(checked: false)
    logger.debug @unchecked_notifications.inspect
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  
end

app/views/admin/customers/index.html.erb
<div class="container">
  <h3 class="text-center mt-5">会員一覧</h3>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>会員ID</th>
        <th>名前</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <% @customers.each do |customer| %>
    <tbody>
      <tr>
        <td><%= customer.id %></td>
        <td>
          <%= link_to admin_customer_path (customer.id) do %>
          <%= customer.name %>
          <% end %>
        </td>
        <td><%= customer.email %></td>
        <td><%= customer.is_deleted ? "退会" : "有効" %></td>
      </tr>
    </tbody>
    <% end %>
  </table>
  <div class="offset-md-5 mt-5"><%= paginate @customers, theme: 'twitter-bootstrap-4' %></div>
</div>

app/views/admin/customers/show.html.erb
<h3 class="text-center mb-5"><%= @customer.name %> さんの投稿</h3>

<table class="table table-borderless mb-5 offset-md-3">
  <tr>
    <td class="font-weight-bold">会員ID</td>
    <td><%= @customer.id %></td>
  </tr>
  <tr>
    <td class="font-weight-bold">名前</td>
    <td><%= @customer.name %></td>
  </tr>
  <tr>
    <td class="font-weight-bold">メールアドレス</td>
    <td><%= @customer.email %></td>
  </tr>
  <tr>
    <td class="font-weight-bold">投稿数</td>
    <td><%= @customer.menus.count %></td>
  </tr>
</table>

<table class="table">
  <thead>
    <tr>
      <th>投稿日</th>
      <th>献立名</th>
      <th>表示する</th>
      <th>投稿を削除</th>
    </tr>
  </thead>
  <tbody>
    <% @menus.each do |menu| %>
    <tr>
      <td><%= menu.created_at.strftime("%Y/%m/%d") %></td>
      <td><%= menu.name %></td>
      <td>
        <%= link_to public_menu_path(menu) do %>
          <div class="show-btn">詳細</div>
        <% end %>
      </td>
      <td><%= link_to "削除", public_menu_path(menu), method: :delete,class: "btn btn-danger", "data-confirm" => "削除しますか？" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<div class="offset-md-5 mt-5">
  <%= paginate @menus, theme: 'twitter-bootstrap-4' %>
</div>

app/views/admin/genres/edit.html.erb
<div class="container mt-5">
  <h3 class="text-center">ジャンル編集</h3>
   <div class="text-center">
     <%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch do |f| %>
       <%= f.text_field :name %>
       <%= f.submit "変更を保存", class: "btn btn-success" %>
     <% end %>
   </div>
</div>

app/views/admin/genres/new.html.erb
<div class="container mt-5 offset-md-3">
  <div class="row">
    <div>
      <h3>ジャンル一覧・追加</h3>
        <%= form_with model: @genre, url: admin_genres_path do |f| %>
          <%= f.text_field :name, placeholder: "ジャンル名" %>
          <%= f.submit "新規登録", class: "btn btn-success" %>
        <% end %>

       <table class="table mt-5">
          <tr class="text-center">
            <td>ジャンル</td>
            <td></td>
            <td></td>
          </tr>
          <% @genres.each do |genre| %>
         <tr>
            <td><%= genre.name %></td>
            <td class="text-right"><%= link_to "編集", edit_admin_genre_path(genre.id), class: "btn btn-warning" %></td>
            <td class="text-right"><%= link_to "削除", admin_genre_path(genre.id), method: :delete, class: "btn btn-danger" %></td>
         </tr>
         <% end %>
       </table>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="text-center">
    <div class="background">
      <div class="background-content">
        <% if customer_signed_in? %>
          <h5 class="text-white pt-5">
            毎日献立を考えるのがめんどすさい！何を作ればいいかわからない！</br>
            そんな時こそ「おまかせルーレット」をご使用ください！</br>
            「おまかせルーレット」はランダムな献立を提示します
          </h5>
          <div class="d-flex justify-content-center">
            <div class="mt-5 mr-5">
              <%= link_to new_public_day_random_path do %>
                <div class="food-btn">1日分の献立</div>
              <% end %>
            </div>
            <div class="mt-5">
              <%= link_to new_public_week_random_path do %>
                <div class="food-btn">1週間分の献立</div>
              <% end %>
            </div>
          </div>
          <% elsif %>
            <h5 class="text-white pt-5">
             登録していただいた方は献立の投稿が可能です</br>
             投稿される方のみ新規登録をお願い致します
            </h5>
            <div class="user-btn d-flex justify-content-center">
              <div class="mt-4 mr-5 mb-5">
                <%= link_to new_customer_registration_path do %>
                  <div class="btn sign_up-btn">新規登録</div>
                <% end %>
              </div>
              <div class="mt-4 mr-5 mb-5">
                <%= link_to new_customer_session_path do %>
                  <div class="btn sign_in-btn">ログイン</div>
                <% end %>
              </div>
              <div class="mt-4 mr-5 mb-5">
                <%= link_to public_guest_sign_in_path, method: :post do %>
                  <div class="btn sign_in-btn">ゲストログイン（閲覧用）</div>
                <% end %>
              </div>
            </div>
            <h5 class="text-white">
             毎日献立を考えるのがめんどくさい！何を作ればいいかわからない！</br>
             そんな時こそ「おまかせルーレット」をご使用ください！</br>
             「おまかせルーレット」はランダムな献立を提示します
            </h5>
            <div class="d-flex justify-content-center">
              <div class="mt-5 mr-5">
                <%= link_to new_public_day_random_path do %>
                  <div class="food-btn">1日分の献立</div>
                <% end %>
              </div>
              <div class="mt-5">
                <%= link_to new_public_week_random_path do %>
                  <div class="food-btn">1週間分の献立</div>
                <% end %>
              </div>
            </div>
        <% end %>
      </div>
   </div>
</div>