config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :customers, only:[:index,:show]
    resources :genres, only:[:new,:create,:edit,:update,:destroy]
    resources :contacts, only:[:index,:edit,:update,:destroy]
    resources :contacts, only:[:index,:new]
  end
  root to: 'homes#top'

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :customer do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations:"public/registrations",
    passwords:'public/settings/passwords',
    sessions:"public/sessions",
    omniauth_callbacks:"public/omniauth_callbacks"
  }


  namespace :public do
    get "/customers/my_page" => "customers#show", as: 'my_page' #会員情報詳細ページ（マイページ）表示
    resources :customers, only:[:edit,:update]
    resources :day_randoms, only:[:new,:create,:show]
    resources :menus, only:[:new,:create,:index,:show,:edit,:update,:destroy]
    resources :week_randoms, only:[:new,:create,:show]
    resources :contacts, only:[:new,:create]
    get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe' #退会確認画面
    patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal' #論理削除用ルーティング
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :customer

  has_many :notifications, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all
    @contacts = Contact.page(params[:page]).order(created_at: :desc).per(10)
    Notification.confirmed
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])
    @contact.update(contact_params)
    @customer = @contact.customer
    ChatMailer.send_when_admin_reply(@customer,@contact).deliver_now
    redirect_to admin_customers_path
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    @contacts = Contact.page(params[:page]).order(created_at: :desc).per(10)
    @customers = Customer.all
    render :index
  end

  private

  def contact_params
    params.require(:contact).permit(:title,:body,:reply)
  end
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/admin/contacts/edit.html.erb
<h2 class="text-center">お問い合わせ内容</h2>
    <%= form_with model: @contact, url: admin_contact_path do |f| %>
    <div class="container">
        <div class="row justify-content-center pt-5">
            <div class="pr-5">
              <div>顧客名: <%= @contact.customer.name %>さん</div>
            </div>
            <div>
              <div>問い合わせ日: <%= @contact.created_at.strftime("%Y年%m月%d日 ") %></div>
            </div>
        </div>
    </div>
    <div class="d-flex justify-content-center">
      <div class="text-left">
        <div class="pt-5">
            <div class="font-weight-bold">タイトル</div>
            <div><%= @contact.title %></div>
        </div>
        <div class="pt-4">
            <div class="font-weight-bold">問い合わせ内容</div>
            <div><%= @contact.body %></div>
        </div>
      </div>
    </div>
    <div class="d-flex justify-content-center pt-5">
        <div class="col-6"><%= f.text_area :reply, class:"form-control", placeholder: "返信内容" %></div>
    </div>
    <div class="text-center pt-3"><%= f.submit "送信", class: "btn btn-primary" %></div>
    <% end %>

app/views/admin/contacts/index.html.erb
<h2 class="text-center">お問い合わせ一覧</h2>
    <table class="table">
    <thead>
        <tr>
           <th>ユーザー名</th>
           <th>問い合わせタイトル</th>
           <th>受信日</th>
           <th></th>
           <th></th>
        </tr>
    </thead>
    <tbody>
    <% @customers.each do |customer| %>
        <% customer.contact.each do |contact| %>
            <tr>
                <td><%= contact.customer.name %></td>
                <td><%= contact.title %></td>
                <td><%= contact.created_at.strftime("%Y年%m月%d日 ") %></td>
                <td><%= link_to "返信", edit_admin_contact_path(contact), class: "btn btn-primary" %></td>
                <td><%= link_to admin_contact_path(contact), method: :delete, class: "btn btn-danger" do %>
                      <i class="fa-solid fa-trash-can"></i>
                    <% end %>
                </td>
            </tr>
        <% end %>
    <% end %>
    </tbody>
</table>