config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :customers, only:[:index,:show]
    resources :genres, only:[:new,:create,:edit,:update,:destroy]
    resources :contacts, only:[:index,:edit,:update,:destroy]
    resources :contacts, only:[:index,:new]
  end
  root to: 'homes#top'

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :customer do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations:"public/registrations",
    passwords:'public/settings/passwords',
    sessions:"public/sessions",
    omniauth_callbacks:"public/omniauth_callbacks"
  }


  namespace :public do
    get "/customers/my_page" => "customers#show", as: 'my_page' #会員情報詳細ページ（マイページ）表示
    resources :customers, only:[:edit,:update]
    resources :day_randoms, only:[:new,:create,:show]
    resources :menus, only:[:new,:create,:index,:show,:edit,:update,:destroy]
    resources :week_randoms, only:[:new,:create,:show]
    resources :contacts, only:[:new,:create]
    get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe' #退会確認画面
    patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal' #論理削除用ルーティング
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :customer

  has_many :notifications, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  has_many:menus, dependent: :destroy
  has_many :contact, dependent: :destroy

  validates :name, presence: true

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def self.guest
    find_or_create_by!(name:'guestuser', email:'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def self.from_omniauth(auth)
    customer = find_by(email: auth.info.email)
    if customer
      customer.update(provider: auth.provider, uid: auth.uid)
    end

    where(provider: auth.provider, uid: auth.uid).first_or_create do |customer|
      customer.name = auth.info.name
      customer.email = auth.info.email
      customer.password = Devise.friendly_token[0,20]
    end
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :menus
  validates :name, presence: true, uniqueness: true
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_one_attached :image
  belongs_to :customer
  belongs_to :genre

  enum food_status: {breakfast:0,lunch:1,dinner:2}

  validates :name, presence: true
  validates :introduction, presence: true
  validates :syusyoku, presence: true
  validates :syusai, presence: true
  validates :fukusai, presence: true
  validates :food_status, presence: true
  validates :genre_id, presence: true
  
end

app/models/notification.rb
class Notification < ApplicationRecord
    
    belongs_to :contact
    
    def self.confirmed
        unchecked_notifications = where(checked: false) 
        unchecked_notifications.each do |un|
          un.update!(checked: true)
        end
    end 
end  

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all
    @contacts = Contact.page(params[:page]).order(created_at: :desc).per(10)
    Notification.confirmed
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])
    @contact.update(contact_params)
    @customer = @contact.customer
    ChatMailer.send_when_admin_reply(@customer,@contact).deliver_now
    redirect_to admin_customers_path
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    @contacts = Contact.page(params[:page]).order(created_at: :desc).per(10)
    @customers = Customer.all
    render :index
  end

  private

  def contact_params
    params.require(:contact).permit(:title,:body,:reply)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def new
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to new_admin_genre_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to new_admin_genre_path
  end
  
  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to request.referer
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :check_notifications
  def check_notifications
    @unchecked_notifications = Notification.where(checked: false)
    logger.debug @unchecked_notifications.inspect
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<% if customer_signed_in? %>
<div>
 <%= render 'public/contacts/new', contact:@contact %>
</div>
<% end %>

app/views/layouts/_header.html.erb
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <div class="navbar-brand">
        <%= link_to root_path do %>
          <%= image_tag 'logo_transparent.png', :size =>'120x120' %>
        <% end %>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-md-auto align-items-center">
          <% if customer_signed_in? %>
            <li>
              <%= link_to destroy_customer_session_path, method: :delete  do %>
                <div class="header-btn">
                  LOG OUT
                </div>
              <% end %>
            </li>
            <li>
              <%= link_to public_my_page_path do %>
                <div class="header-btn">
                  MY PAGE
                </div>
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>
                <div class="header-btn">
                  TOP
                </div>
              <% end %>
            </li>
            <li>
              <%= link_to new_public_menu_path do %>
                <div class="header-btn">
                  NEW MENU
                </div>
              <% end %>
            </li>
          <% elsif admin_signed_in? %>
            <li>
              <%= link_to destroy_admin_session_path, method: :delete do %>
                <div class="header-btn">
                  LOG OUT
                </div>
              <% end %>
            </li>
            <li>
              <%= link_to new_admin_genre_path do %>
                <div class="header-btn">
                  GENRE
                </div>
              <% end %>
            </li>
            <li>
              <%= link_to admin_customers_path do %>
                <div class="header-btn">
                  MEMBERS
                </div>
              <% end %>
            </li>
            <li>
              <%= link_to admin_contacts_path do %>
                <div class="header-btn">
                  <% if @unchecked_notifications.any? %>
                    <i class="fa-solid fa-bell notification-icon fa-lg"></i>MAIL
                  <% else %>
                    MAIL
                  <% end %>
                </div>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OmakaseRoulette</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/900e5c76da.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= render 'layouts/header' %>
      <p class="notice text-center"><%= notice %></p>
      <p class="alert text-center"><%= alert %></p>
    </header>
    <main>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>